kind: pipeline
name: spring-framework

steps:
  - name: notify-build-started
    image: registry.airwallex.com/airwallex-buildbot:latest
    settings:
      channel: global-drone-builds
      position: PreBuild
      author: ${DRONE_COMMIT_AUTHOR}
    when:
      status:  [ failure, success ]

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
  - name: gradle-cache
    host:
      path: /Storage/Gradle-Cache
  - name: root-m2
    host:
      path: /Storage/Maven-Cache
