kind: pipeline
name: spring-framework

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: rails-prod-monitor
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
        {{build.link}}
      {{else}}
        build {{build.number}} failed. Fix me please.
        {{build.link}}
      {{/success}}

volumes:
- name: docker-sock
  host:
    path: /var/run/docker.sock
- name: gradle-cache
  host:
    path: /Storage/Gradle-Cache
- name: root-m2
  host:
    path: /Storage/Maven-Cache
- name: report
  host:
    path: /Storage/unit-tests
