kind: pipeline
name: spring-framework

pipeline:
  docker-info:
    docker:
    image: registry.airwallex.com/drone-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker info

  notify-build-started:
    image: registry.airwallex.com/airwallex-buildbot:latest
    channel: global-drone-builds
    position: PreBuild
    author: ${DRONE_COMMIT_AUTHOR}
    when:
      status:  [ failure, success ]
