kind: pipeline
name: spring-framework

  clone:
    image: peterdavehello/cdnjs-drone-ci
    sparseCheckout: tools/sparse-checkout.template
  bot-review:
    image: peterdavehello/drone-github-status-report-bot:latest
    when:
      event: pull_request
      status: [ success, failure ]
